
language: java
jdk:
  - openjdk8

branches:
  only:
    - master

#Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r cellar-reporter-service *
  - mkdir -p deploy
  - mv cellar-reporter-service.zip deploy/cellar-reporter-service.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings 에 설절된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings 에 설정된 값
    bucket: cellar-reporter-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근 private
    local_dir: deploy # before_deploy 에서 생성한 디렉토리
    wait-until-deployed: true

#CI 실행완료 시 메일로 알람
notifications:
  email:
    recipients:
      - sokinowen@gmail.com
